import { lazy, type ComponentType, type LazyExoticComponent } from 'react';
import type { TemplateData } from './types';

export interface TemplateProps {
  data?: TemplateData;
}

export interface TemplateMeta {
  slug: string;
  name: string;
  /** Short style label, e.g. "Swiss editorial". */
  style: string;
  blurb: string;
  /** 3–4 swatch colors for the gallery card. */
  swatch: string[];
  accent: string;
  bg: string;
  ink: string;
  theme: 'light' | 'dark';
  /** Display name of the headline typeface (for the card type-preview). */
  font: string;
  /** Concept-relevant photo for the gallery/design thumbnail. */
  thumb?: string;
  Component: LazyExoticComponent<ComponentType<TemplateProps>>;
}

export const TEMPLATES: TemplateMeta[] = [
  {
    slug: 'mumotor',
    name: 'Mumotor',
    style: 'Mumotor signature',
    blurb: 'The Mumotor look — clean white, one calm accent and soft aurora. Tap the colour dots to recolour the whole site.',
    swatch: ['#FFFFFF', '#0071E3', '#1D1D1F', '#F5F5F7'],
    accent: '#0071E3',
    bg: '#FFFFFF',
    ink: '#1D1D1F',
    theme: 'light',
    font: 'Inter',
    thumb: 'https://images.unsplash.com/photo-1596649714492-a8f90ecb3776?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./mumotor')),
  },
  {
    slug: 'meridian',
    name: 'Meridian',
    style: 'Topographic survey',
    blurb: 'An atlas plate — engraved serif titles, contour hairlines and a route line that draws itself down the page as you scroll.',
    swatch: ['#E6E7E0', '#B03060', '#A8AC9E', '#2E6E7E'],
    accent: '#B03060',
    bg: '#E6E7E0',
    ink: '#1A1F1D',
    theme: 'light',
    font: 'Instrument Serif',
    thumb: 'https://images.unsplash.com/photo-1736117704452-46670dd0c81f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./meridian')),
  },
  {
    slug: 'bezel',
    name: 'Bezel',
    style: 'Machined instrument',
    blurb: 'Precision-engineered — milled charcoal panels, knurled edges and stat dials whose needles sweep up like a real gauge.',
    swatch: ['#16181B', '#E5484D', '#8E9299', '#24272B'],
    accent: '#E5484D',
    bg: '#16181B',
    ink: '#EDEBE6',
    theme: 'dark',
    font: 'Familjen Grotesk',
    thumb: 'https://images.unsplash.com/photo-1498887960847-2a5e46312788?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./bezel')),
  },
  {
    slug: 'solari',
    name: 'Solari',
    style: 'Split-flap departures',
    blurb: 'A mechanical departure board — brushed brass, amber flaps and words that clatter into place as you scroll.',
    swatch: ['#17140F', '#F5A623', '#8C7A4B', '#221D16'],
    accent: '#F5A623',
    bg: '#17140F',
    ink: '#EDE7D8',
    theme: 'dark',
    font: 'Oswald',
    thumb: 'https://images.unsplash.com/photo-1769054514579-593ffd690aff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./solari')),
  },
  {
    slug: 'cadence',
    name: 'Cadence',
    style: 'Kinetic typography',
    blurb: 'Type is the whole design — oversized letters that lean and thicken with your scroll speed, over a reversing marquee.',
    swatch: ['#F1EFE9', '#2E22CE', '#141318', '#E4E1D8'],
    accent: '#2E22CE',
    bg: '#F1EFE9',
    ink: '#141318',
    theme: 'light',
    font: 'Roboto Flex',
    thumb: 'https://images.unsplash.com/photo-1554830909-a838f1634c17?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./cadence')),
  },
  {
    slug: 'circuit',
    name: 'Circuit',
    style: 'Motorsport telemetry',
    blurb: 'A pit-wall broadcast — a car laps a hand-drawn circuit as you scroll while a live timing tower ticks off the sectors.',
    swatch: ['#0C0D10', '#FF2E3D', '#37E07A', '#15171C'],
    accent: '#FF2E3D',
    bg: '#0C0D10',
    ink: '#EDF1F5',
    theme: 'dark',
    font: 'Saira',
    thumb: 'https://images.unsplash.com/photo-1777362039145-efdcd02eb988?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./circuit')),
  },
  {
    slug: 'press',
    name: 'Press',
    style: 'Letterpress print',
    blurb: 'A fine letterpress prospectus — type debossed into cotton paper, copper fleurons and a wax seal that stamps as you scroll.',
    swatch: ['#F1EBDD', '#1F4D3D', '#A8763E', '#1B1A18'],
    accent: '#1F4D3D',
    bg: '#F1EBDD',
    ink: '#1B1A18',
    theme: 'light',
    font: 'Libre Caslon Display',
    thumb: 'https://images.unsplash.com/photo-1552333331-6bb4a9c1e62a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./press')),
  },
  {
    slug: 'reel',
    name: 'Reel',
    style: '35mm cinema',
    blurb: 'A film print — letterboxed hero, a sprocket-holed filmstrip that scrubs frame-by-frame as you scroll and an academy-leader countdown.',
    swatch: ['#0B0B0D', '#E5533D', '#C9A24B', '#16161A'],
    accent: '#E5533D',
    bg: '#0B0B0D',
    ink: '#F4F1EA',
    theme: 'dark',
    font: 'Bebas Neue',
    thumb: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./reel')),
  },
  {
    slug: 'slate',
    name: 'Slate',
    style: 'Chalkboard classroom',
    blurb: 'A schoolroom blackboard — hand-drawn chalk road diagrams that draw themselves, eraser-wipe transitions and a wooden chalk ledge.',
    swatch: ['#1E2622', '#E4897B', '#A9C0A0', '#24302B'],
    accent: '#E4897B',
    bg: '#1E2622',
    ink: '#EDEAE0',
    theme: 'dark',
    font: 'Newsreader',
    thumb: 'https://images.unsplash.com/photo-1695923142527-9b43a467b298?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./slate')),
  },
  {
    slug: 'primary',
    name: 'Primary',
    style: 'Bauhaus geometry',
    blurb: 'A Bauhaus poster — flat circles, triangles and bars in primary colours that assemble as you scroll. Graphic and confident.',
    swatch: ['#F0E9DA', '#2340D9', '#DE3B26', '#F2B705'],
    accent: '#2340D9',
    bg: '#F0E9DA',
    ink: '#161514',
    theme: 'light',
    font: 'Jost',
    thumb: 'https://images.unsplash.com/photo-1773813964871-a0c1ca66dac3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./primary')),
  },
  {
    slug: 'gallery',
    name: 'Gallery',
    style: 'Museum exhibition',
    blurb: 'The work as a curated exhibition — framed prints with museum wall-labels and a spotlight that follows you down the wall.',
    swatch: ['#EEEAE1', '#B5662E', '#2A2622', '#E3DCCF'],
    accent: '#B5662E',
    bg: '#EEEAE1',
    ink: '#1C1A17',
    theme: 'light',
    font: 'Cormorant',
    thumb: 'https://images.unsplash.com/photo-1606819717115-9159c900370b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./gallery')),
  },
  {
    slug: 'gilt',
    name: 'Gilt',
    style: 'Foil-stamped luxury',
    blurb: 'A foil-stamped invitation — deep charcoal, champagne-gold headlines with a sheen that rakes across them as you scroll.',
    swatch: ['#17161B', '#C7A96B', '#8A6E3C', '#1F1E24'],
    accent: '#C7A96B',
    bg: '#17161B',
    ink: '#EFE9DD',
    theme: 'dark',
    font: 'Marcellus',
    thumb: 'https://images.unsplash.com/photo-1545873681-d8affd67677b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./gilt')),
  },
  {
    slug: 'sumi',
    name: 'Sumi',
    style: 'Sumi-e ink wash',
    blurb: 'A sumi-e brush painting — warm washi paper, a hand-brushed enso that draws itself and a vermilion hanko seal that stamps as you scroll.',
    swatch: ['#F2EEE4', '#C4392E', '#8A857A', '#E7E1D3'],
    accent: '#C4392E',
    bg: '#F2EEE4',
    ink: '#1A1815',
    theme: 'light',
    font: 'Zen Old Mincho',
    thumb: 'https://images.unsplash.com/photo-1762114974446-385ed570b26e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./sumi')),
  },
  {
    slug: 'console',
    name: 'Console',
    style: 'Product OS',
    blurb: 'A developer-grade product console — a ⌘K command palette that types itself, live dashboard widgets and crisp indigo accents on near-black.',
    swatch: ['#0E1013', '#5B8CFF', '#7A8290', '#171A1F'],
    accent: '#5B8CFF',
    bg: '#0E1013',
    ink: '#E7EAEE',
    theme: 'dark',
    font: 'Inter Tight',
    thumb: 'https://images.unsplash.com/photo-1650661926447-9efb2610f64c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./console')),
  },
  {
    slug: 'transit',
    name: 'Transit',
    style: 'Metro wayfinding',
    blurb: 'A transit signage system — a bold coloured line threads the page past roundel stops while a live service marker travels it as you scroll.',
    swatch: ['#F5F6F8', '#1F5FE0', '#E11D48', '#E9EBEF'],
    accent: '#1F5FE0',
    bg: '#F5F6F8',
    ink: '#16181D',
    theme: 'light',
    font: 'Overpass',
    thumb: 'https://images.unsplash.com/photo-1679868475485-d6b1194d019b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./transit')),
  },
  {
    slug: 'ledger',
    name: 'Ledger',
    style: 'Fintech statement',
    blurb: 'A neobank statement — a crisp figures card with tabular numerals that count up, a sparkline that draws itself and trustworthy emerald accents.',
    swatch: ['#F7F7F4', '#0E7C66', '#62625A', '#EAE9E3'],
    accent: '#0E7C66',
    bg: '#F7F7F4',
    ink: '#14140F',
    theme: 'light',
    font: 'Manrope',
    thumb: 'https://images.unsplash.com/photo-1616077168712-fc6c788db4af?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./ledger')),
  },
  {
    slug: 'grid-ink',
    name: 'Grid & Ink',
    style: 'Swiss editorial',
    blurb: 'Strict typographic grid, hairline rules and numbered sections. Confident, magazine-grade, zero clutter.',
    swatch: ['#FAFAF7', '#111111', '#E4002B', '#6B6B6B'],
    accent: '#E4002B',
    bg: '#FAFAF7',
    ink: '#111111',
    theme: 'light',
    font: 'Archivo',
    thumb: 'https://images.unsplash.com/photo-1617050318658-a9a3175e34cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./grid-ink')),
  },
  {
    slug: 'open-road',
    name: 'Open Road',
    style: 'Retro automotive',
    blurb: 'Warm 70s road-trip energy — sunburst hero, enamel badges, grain and dashed-road dividers.',
    swatch: ['#F4E9D8', '#D2691E', '#E0A526', '#2A6F6B'],
    accent: '#D2691E',
    bg: '#F4E9D8',
    ink: '#3A2A1E',
    theme: 'light',
    font: 'Abril Fatface',
    thumb: 'https://images.unsplash.com/photo-1556028475-50d7afb5029b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=900',
    Component: lazy(() => import('./open-road')),
  },
];

export function getTemplate(slug: string | undefined): TemplateMeta | undefined {
  return TEMPLATES.find((t) => t.slug === slug);
}

export function getTemplateIndex(slug: string | undefined): number {
  return TEMPLATES.findIndex((t) => t.slug === slug);
}
